### ISSUE TITLE
AM / PM is registered as separator

### ISSUE THREAD

**Issue by asgerb** [tomasc/semantic_date_time_tags#1]
When using AM/PM for Time displays:
```yaml
en:
  time:
    formats:
      full: "%I.%M %p"
```
AM/PM is tagged as a separator:
```html
<time class="semantic time whole_hour whole_minute">
<span class="hours I">10</span><span class="sep">.</span><span class="minutes M">00</span> <span class="sep">AM</span>
</time>
```
