### ISSUE TITLE
Allow passing locale scope to tags

### ISSUE THREAD

**Issue by asgerb** [tomasc/semantic_date_time_tags#3]
Would be nice to be able to do this:
```Ruby
semantic_date_tag(date, :events)
```
Which would then fetch the locale from that scope
```
en:
  events:
    date:
      formats:
        full: "%-d.%-m.%Y"
```
